from pydantic import BaseModel, Field
from typing import List, Optional, Literal

class TaskRequest(BaseModel):
    task: str = Field(..., description="Description of the task to break down")
    validate_searches: bool = Field(default=False, description="Whether to validate searches with Google")

class SearchResult(BaseModel):
    title: str
    link: str
    snippet: str

class SearchValidation(BaseModel):
    is_verified: bool
    search_results: List[SearchResult]
    recommended_result: Optional[int] = None

class Step(BaseModel):
    step_number: int
    description: str
    search_query: str
    expected_results: str
    key_phrases: List[str]
    alternative_searches: List[str]
    instructions: str
    validation: Optional[SearchValidation] = None

class WorkflowResponse(BaseModel):
    task: str
    task_summary: str
    simple_explanation: str  # NEW FIELD
    steps: List[Step]
    total_steps: int
    estimated_time: str
    difficulty: str

class AnnotationAction(BaseModel):
    """Single annotation action for a step"""
    action_type: Literal["click", "right_click", "input", "drag", "key_press", "scroll", "hover"]
    description: str

class StepAnnotationSequence(BaseModel):
    """Annotation sequence for a single step"""
    step_number: int
    step_description: str  # Generated by Claude based on the task
    search_query: str
    expected_actions: List[AnnotationAction]  # Claude predicts likely actions
    estimated_duration_seconds: int

class WorkflowAnnotationSequence(BaseModel):
    """Complete annotation sequence for the entire workflow"""
    task: str
    task_summary: str
    total_steps: int
    annotation_sequences: List[StepAnnotationSequence]
    total_estimated_actions: int
    annotation_guidelines: str  # Generated by Claude for this task

